In [1]:
import sys
sys.path.append("..") # This will allow to fix import issues.[to be changed]

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from tools import eda
from tools import preprocess as prep
from tools import all_steps

In [2]:
path_train = './splice/splice.fold.000000.train.arff' # [to be changed]
path_test = './splice/splice.fold.000000.test.arff' # [to be changed]
df_train = eda.read_arff(path_data=path_train)
df_test = eda.read_arff(path_data=path_test)

df_train.head()
# X_num, X_cat, y = all_steps.clean_cmc(df)

# X = prep.join_features(X_num, X_cat)

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60,Class
0,b'A',b'A',b'T',b'A',b'T',b'C',b'A',b'A',b'C',b'G',...,b'T',b'C',b'T',b'C',b'C',b'T',b'G',b'G',b'A',b'EI'
1,b'G',b'C',b'G',b'T',b'C',b'C',b'C',b'G',b'C',b'T',...,b'G',b'G',b'C',b'A',b'A',b'A',b'G',b'G',b'C',b'IE'
2,b'G',b'G',b'G',b'G',b'T',b'G',b'A',b'A',b'A',b'G',...,b'A',b'G',b'A',b'A',b'G',b'A',b'T',b'T',b'C',b'N'
3,b'G',b'G',b'G',b'G',b'A',b'A',b'A',b'A',b'C',b'A',...,b'C',b'A',b'A',b'A',b'T',b'G',b'C',b'A',b'A',b'N'
4,b'C',b'C',b'C',b'C',b'A',b'C',b'C',b'C',b'C',b'T',...,b'C',b'A',b'C',b'C',b'A',b'A',b'G',b'A',b'C',b'IE'

In [3]:
df_test.head()

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60,Class
0,b'C',b'A',b'T',b'T',b'C',b'T',b'C',b'A',b'C',b'A',...,b'G',b'C',b'T',b'T',b'G',b'A',b'A',b'A',b'G',b'N'
1,b'C',b'C',b'C',b'C',b'A',b'A',b'C',b'T',b'T',b'G',...,b'G',b'C',b'A',b'G',b'C',b'C',b'A',b'G',b'G',b'N'
2,b'G',b'C',b'T',b'G',b'C',b'G',b'C',b'C',b'T',b'T',...,b'G',b'G',b'G',b'G',b'C',b'C',b'A',b'G',b'G',b'EI'
3,b'T',b'G',b'T',b'C',b'T',b'G',b'A',b'A',b'T',b'T',...,b'C',b'C',b'C',b'A',b'C',b'C',b'A',b'T',b'C',b'IE'
4,b'A',b'T',b'C',b'C',b'T',b'G',b'T',b'G',b'T',b'T',...,b'T',b'G',b'T',b'T',b'T',b'G',b'A',b'C',b'C',b'IE'

In [8]:
target = 'Class'
features = [col for col in df_train.columns if col != target]
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
# label_encoder = label_encoder.fit()
y_encoded = pd.DataFrame(label_encoder.fit_transform(df_train[target]), 
                         columns=['Class'])


df_OHE_train = prep.encode(df_train[features])
df_OHE_train.head()

Binary cat_features: []
Remaining cat_features: ['attribute_1', 'attribute_2', 'attribute_3', 'attribute_4', 'attribute_5', 'attribute_6', 'attribute_7', 'attribute_8', 'attribute_9', 'attribute_10', 'attribute_11', 'attribute_12', 'attribute_13', 'attribute_14', 'attribute_15', 'attribute_16', 'attribute_17', 'attribute_18', 'attribute_19', 'attribute_20', 'attribute_21', 'attribute_22', 'attribute_23', 'attribute_24', 'attribute_25', 'attribute_26', 'attribute_27', 'attribute_28', 'attribute_29', 'attribute_30', 'attribute_31', 'attribute_32', 'attribute_33', 'attribute_34', 'attribute_35', 'attribute_36', 'attribute_37', 'attribute_38', 'attribute_39', 'attribute_40', 'attribute_41', 'attribute_42', 'attribute_43', 'attribute_44', 'attribute_45', 'attribute_46', 'attribute_47', 'attribute_48', 'attribute_49', 'attribute_50', 'attribute_51', 'attribute_52', 'attribute_53', 'attribute_54', 'attribute_55', 'attribute_56', 'attribute_57', 'attribute_58', 'attribute_59', 'attribute_60']

,attribute_1_b'A',attribute_1_b'C',attribute_1_b'D',attribute_1_b'G',attribute_1_b'T',attribute_2_b'A',attribute_2_b'C',attribute_2_b'D',attribute_2_b'G',attribute_2_b'T',...,attribute_58_b'G',attribute_58_b'T',attribute_59_b'A',attribute_59_b'C',attribute_59_b'G',attribute_59_b'T',attribute_60_b'A',attribute_60_b'C',attribute_60_b'G',attribute_60_b'T'
0,1,0,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
1,0,0,0,1,0,0,1,0,0,0,...,1,0,0,0,1,0,0,1,0,0
2,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,1,0,1,0,0
3,0,0,0,1,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
4,0,1,0,0,0,0,1,0,0,0,...,1,0,1,0,0,0,0,1,0,0

In [5]:
df_OHE_test = prep.encode(df_test[features])
df_OHE_test.head()

Binary cat_features: []
Remaining cat_features: ['attribute_1', 'attribute_2', 'attribute_3', 'attribute_4', 'attribute_5', 'attribute_6', 'attribute_7', 'attribute_8', 'attribute_9', 'attribute_10', 'attribute_11', 'attribute_12', 'attribute_13', 'attribute_14', 'attribute_15', 'attribute_16', 'attribute_17', 'attribute_18', 'attribute_19', 'attribute_20', 'attribute_21', 'attribute_22', 'attribute_23', 'attribute_24', 'attribute_25', 'attribute_26', 'attribute_27', 'attribute_28', 'attribute_29', 'attribute_30', 'attribute_31', 'attribute_32', 'attribute_33', 'attribute_34', 'attribute_35', 'attribute_36', 'attribute_37', 'attribute_38', 'attribute_39', 'attribute_40', 'attribute_41', 'attribute_42', 'attribute_43', 'attribute_44', 'attribute_45', 'attribute_46', 'attribute_47', 'attribute_48', 'attribute_49', 'attribute_50', 'attribute_51', 'attribute_52', 'attribute_53', 'attribute_54', 'attribute_55', 'attribute_56', 'attribute_57', 'attribute_58', 'attribute_59', 'attribute_60']

,attribute_1_b'A',attribute_1_b'C',attribute_1_b'G',attribute_1_b'T',attribute_2_b'A',attribute_2_b'C',attribute_2_b'G',attribute_2_b'T',attribute_3_b'A',attribute_3_b'C',...,attribute_59_b'A',attribute_59_b'C',attribute_59_b'G',attribute_59_b'N',attribute_59_b'T',attribute_60_b'A',attribute_60_b'C',attribute_60_b'G',attribute_60_b'N',attribute_60_b'T'
0,0,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
1,0,1,0,0,0,1,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
2,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
3,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
4,1,0,0,0,0,0,0,1,0,1,...,0,1,0,0,0,0,1,0,0,0

In [9]:
# dummies_frame = pd.get_dummies(df)
df_OHE_train = df_OHE_train.reindex(columns = df_OHE_test.columns, fill_value=0)
df_OHE_train.head()

,attribute_1_b'A',attribute_1_b'C',attribute_1_b'G',attribute_1_b'T',attribute_2_b'A',attribute_2_b'C',attribute_2_b'G',attribute_2_b'T',attribute_3_b'A',attribute_3_b'C',...,attribute_59_b'A',attribute_59_b'C',attribute_59_b'G',attribute_59_b'N',attribute_59_b'T',attribute_60_b'A',attribute_60_b'C',attribute_60_b'G',attribute_60_b'N',attribute_60_b'T'
0,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
2,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,1,0,0,0,0
4,0,1,0,0,0,1,0,0,0,1,...,1,0,0,0,0,0,1,0,0,0

## Another approach

In [10]:
from sklearn.preprocessing import OneHotEncoder

ohe= OneHotEncoder(handle_unknown='ignore', sparse=False)
ohe.fit(df_train[features])

# now let's simulate the two situations A and B
# df.loc[1, 'x']= 1
# df= df.append(dict(x=5, y=5), ignore_index=True)

# the actual feature generation is done in a separate step
training = ohe.transform(df_train[features])
training.shape

# if you need the columns in your existing data frame, you can glue them together
# df2=pd.DataFrame(tr, columns=['oh1', 'oh2', 'oh3'], index=df.index)
# result= pd.concat([df, df2], axis='columns')

(2868, 255)

In [11]:
target = 'Class'
features_test = [col for col in df_train.columns if col != target]
testing = ohe.transform(df_test[features_test])
testing.shape

(322, 255)